# Generated by Django 2.2 on 2019-07-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hy_case', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseData',
        ),
    ]
