# Generated by Django 2.2 on 2019-07-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hy_case', '0002_delete_casedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_person', models.CharField(max_length=32, unique=True)),
                ('case_nature', models.CharField(max_length=128)),
                ('case_address', models.CharField(max_length=128)),
                ('case_date', models.CharField(max_length=32)),
                ('case_price', models.CharField(max_length=32)),
                ('case_detail', models.CharField(max_length=512)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '案件',
                'verbose_name_plural': '案件',
                'ordering': ['-c_time'],
            },
        ),
    ]
