# Generated by Django 2.2 on 2019-07-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hy_case', '0004_auto_20190703_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedata',
            name='case_carton',
            field=models.CharField(default=0, max_length=32),
        ),
        migrations.AddField(
            model_name='casedata',
            name='case_trans',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
