# Generated by Django 2.2 on 2019-07-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hy_case', '0005_auto_20190712_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedata',
            name='case_key',
            field=models.CharField(default=0, max_length=32, unique=True),
        ),
    ]
