# Generated by Django 2.2 on 2019-07-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hy_case', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=256),
        ),
    ]
