# Generated by Django 2.2 on 2019-08-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hy_case', '0009_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-cust_key'], 'verbose_name': '零售户', 'verbose_name_plural': '零售户'},
        ),
    ]
