# Generated by Django 2.2 on 2019-08-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hy_case', '0010_auto_20190821_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cust_district',
            field=models.CharField(default='', max_length=32),
        ),
    ]
