# Generated by Django 2.2 on 2019-09-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hy_case', '0011_customer_cust_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cust_licenseId',
            field=models.CharField(default='', max_length=64),
        ),
    ]
