# Generated by Django 2.2 on 2019-09-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hy_case', '0012_customer_cust_licenseid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clues',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('c_car', models.CharField(max_length=32)),
                ('c_main_addr', models.CharField(max_length=128)),
                ('c_relate_addr', models.CharField(max_length=128)),
                ('c_uptime', models.CharField(max_length=32)),
                ('c_model_time', models.DateTimeField(auto_now_add=True)),
                ('c_type', models.CharField(max_length=32)),
                ('c_amount', models.CharField(max_length=32)),
                ('c_info', models.CharField(max_length=256)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hy_case.Customer')),
            ],
            options={
                'verbose_name': '线索',
                'verbose_name_plural': '线索',
                'ordering': ['-c_model_time'],
            },
        ),
    ]
