# Generated by Django 2.2 on 2019-10-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hy_case', '0013_clues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clues',
            options={'ordering': ['-c_time'], 'verbose_name': '线索', 'verbose_name_plural': '线索'},
        ),
        migrations.RenameField(
            model_name='clues',
            old_name='c_amount',
            new_name='c_case_amount',
        ),
        migrations.RenameField(
            model_name='clues',
            old_name='c_type',
            new_name='c_case_type',
        ),
        migrations.RenameField(
            model_name='clues',
            old_name='c_uptime',
            new_name='c_get_time',
        ),
        migrations.RenameField(
            model_name='clues',
            old_name='c_model_time',
            new_name='c_time',
        ),
        migrations.AddField(
            model_name='clues',
            name='c_clue_type',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='clues',
            name='c_detail_addr',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_type',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='clues',
            name='c_car',
            field=models.CharField(max_length=64),
        ),
    ]
