# Generated by Django 2.2 on 2019-10-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hy_case', '0015_auto_20191022_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_clue', to='hy_case.Customer'),
        ),
    ]
