# Generated by Django 2.2 on 2019-10-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hy_case', '0016_auto_20191022_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cust_district',
        ),
    ]
