# Generated by Django 2.2 on 2019-11-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hy_case', '0017_remove_customer_cust_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='c_car',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='clues',
            name='c_case_amount',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='clues',
            name='c_case_type',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='clues',
            name='c_get_time',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='clues',
            name='c_info',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='clues',
            name='c_main_addr',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='clues',
            name='c_relate_addr',
            field=models.CharField(default='', max_length=128),
        ),
    ]
